name: cvi-project
channels:
  - defaults
dependencies:
  # Conda packages (from conda channels)
  - _tflow_select=2.3.0=gpu
  - absl-py=0.14.0
  - aiohttp=3.7.4.post0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=21.2.0
  - blinker=1.4
  - brotlipy=0.7.0
  - ca-certificates=2021.5.30
  - cachetools=4.2.2
  - certifi=2021.5.30
  - cffi=1.14.6
  - chardet=4.0.0
  - click=8.0.1
  - colorama=0.4.4
  - cryptography=3.4.7
  - dataclasses=0.8
  - gast=0.4.0
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpcio=1.38.1
  - h5py=2.10.0
  - hdf5=1.10.6
  - idna=2.10
  - importlib-metadata=4.8.1
  - intel-openmp=2021.3.0
  - joblib=1.0.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - krb5=1.19.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - liblapack=3.9.0
  - libprotobuf=3.18.0
  - libssh2=1.10.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.4
  - mkl=2021.3.0
  - msys2-conda-epoch=20160418
  - multidict=5.1.0
  - numpy=1.21.2
  - oauthlib=3.1.1
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - pip=21.2.4
  - protobuf=3.18.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyreadline=2.1
  - pysocks=1.7.1
  - python=3.8.12
  - python_abi=3.8
  - pyu2f=0.1.5
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.7.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tbb=2021.3.0
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.0
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.5.0
  - tensorflow-gpu=2.3.0
  - termcolor=1.1.0
  - tk=8.6.11
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - ucrt=10.0.20348.0
  - urllib3=1.26.7
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - werkzeug=2.0.1
  - wheel=0.37.0
  - win_inet_pton=1.1.0
  - wrapt=1.12.1
  - yarl=1.6.3
  - zipp=3.5.0
  - zlib=1.2.11
  
  # Required for pip packages
  - pip
  
  # Pip packages (originally from PyPI)
  - pip:
    - bidict==0.21.3
    - cycler==0.10.0
    - dnspython==2.1.0
    - eventlet==0.25.1
    - flask==1.1.2
    - flask-socketio==3.3.1
    - greenlet==1.1.1
    - imageio==2.9.0
    - imgaug==0.4.0
    - itsdangerous==2.0.1
    - jinja2==3.0.1
    - markupsafe==2.0.1
    - monotonic==1.6
    - networkx==2.6.3
    - pandas==1.2.4
    - python-engineio==3.8.2.post1
    - python-socketio==4.2.1
    - pytz==2021.1
    - pywavelets==1.1.1
    - scikit-image==0.18.3
    - scikit-learn==0.24.2
    - shapely==1.7.1
    - threadpoolctl==2.2.0
    - tifffile==2021.8.30